{% set name = "requests-gssapi" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d52bf8c2aa2a829130efcca85c14943fdd0aa75455aab985b2b8726159c20ca

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - python-gssapi
    - requests >=1.1.0

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show requests-gssapi
    # run tests
    - python -m pytest -ra -v tests/

about:
  home: https://github.com/pythongssapi/requests-gssapi
  dev_url: https://github.com/pythongssapi/requests-gssapi.git
  summary: A GSSAPI authentication handler for python-requests
  license: ISC
  license_file: LICENSE
  description: |
    Requests is an HTTP library, written in Python, for human beings.
    This library adds optional GSSAPI authentication support and supports
    mutual authentication.

    It provides a fully backward-compatible shim for the old
    python-requests-kerberos library: simply replace `import requests_kerberos`
    with `import requests_gssapi`.
    A more powerful interface is provided by the HTTPSPNEGOAuth component,
    but this is of course not guaranteed to be compatible.

extra:
  recipe-maintainers:
    - duncanmmacleod
